### ISSUE TITLE
how count distance 2 polygon?

### ISSUE THREAD

**Issue by xor256** [shanebdavis/gui_geometry#1]
for example 
![bitmap](https://user-images.githubusercontent.com/17579697/37389892-50992a6a-2766-11e8-9ffa-79b73bb920c7.png)

**Comment by shanebdavis** [comment]
This library doesn’t have direct support for polygons other than coordinate-aligned rectangles. Rectangle B in your example can’t be fully represented by the library’s rectangle construct.

You could use a list of points for each of your polygons, but computing distance between them is beyond the scope of this library. You’ll need to research the computer science algorithms out there to figure out how to determine the distance between two polygons given a list of points.

Sorry I can’t be more helpful.

**Comment by xor256** [comment]
ok
